### PR TITLE
Tutorial: Change the names of groups of columns from 'column' to 'row'

### PR DESCRIPTION
**Pull request by patrickmn**
I'm new to Opaleye so please feel free to shut this down ruthlessly on the grounds of ignorance.

I was a little confused by the terminology in the tutorials in that rows are referred to as columns. Is this actually because they are "functorially" equivalent?

### CODE REVIEW

**Comment by patrickmn** [comment]
Seems like it. Would it be worth adding a note to the documentation explaining this?

**Comment by tomjaguarpaw** [comment]
> Seems like it.

What seems like what?

**Comment by patrickmn** [comment]
It seemed to be a common idiom, and I thought I was missing something obvious.

I agree `Columns` would be clearer too.

I can leave this PR open for discussion, or close it and open an issue.

**Comment by tomjaguarpaw** [comment]
Probably best to close it and open an issue referencing this PR.

**Pull request closed without merging**
