### PR TITLE
Upsert

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
An updated version of https://github.com/tomjaguarpaw/haskell-opaleye/pull/382

**Comment by tomjaguarpaw** [comment]
I squashed a bunch of patches.  Nearly ready to merge.

**Comment by tomjaguarpaw** [comment]
Thanks @dfithian and @AnthonySuper !

**Comment by dfithian** [comment]
@tomjaguarpaw Are there plans for a release for this? Upgrading LTS right now but I can still use the commit hash for a while.

**Comment by tomjaguarpaw** [comment]
I have a few things I'm trying to add to Opaleye at once.  I could do a release of this in the next few days if it's really important to you.

**Comment by dfithian** [comment]
That's okay, we can wait! Do your thing.

**Pull request merged**
