### PR TITLE
compatibility fixes for GHC 8.4.x

### LINKED ISSUE #394: Ambiguous Occurrence
Doing a simple `cabal install opaleye` on OSX with GHC 8.4.3 yields an "ambiguous occurrence" error for `<>`

```
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Resolving dependencies...
Configuring opaleye-0.6.7000.0...
Building opaleye-0.6.7000.0...
Failed to install opaleye-0.6.7000.0
Build log ( ~/.cabal/logs/ghc-8.4.3/opaleye-0.6.7000.0-2zLcmx53TlnJY34QVAuO33.log ):
cabal: Entering directory '/var/folders/kv/4xxz5fvd7jq8pwkkr4j1dlj40000gn/T/cabal-tmp-46623/opaleye-0.6.7000.0'
Configuring opaleye-0.6.7000.0...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Preprocessing library for opaleye-0.6.7000.0..
Building library for opaleye-0.6.7000.0..
[ 1 of 53] Compiling Opaleye.Internal.HaskellDB.Sql ( src/Opaleye/Internal/HaskellDB/Sql.hs, dist/build/Opaleye/Internal/HaskellDB/Sql.o )
[ 2 of 53] Compiling Opaleye.Internal.HaskellDB.Sql.Print ( src/Opaleye/Internal/HaskellDB/Sql/Print.hs, dist/build/Opaleye/Internal/HaskellDB/Sql/Print.o )

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:123:39: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
123 |     Just sn -> doubleQuotes (text sn) <> text "." <> tname
    |                                       ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:123:51: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
123 |     Just sn -> doubleQuotes (text sn) <> text "." <> tname
    |                                                   ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:160:54: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
160 |       CompositeSqlExpr s x   -> parens (ppSqlExpr s) <> text "." <> text x
    |                                                      ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:160:66: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
160 |       CompositeSqlExpr s x   -> parens (ppSqlExpr s) <> text "." <> text x
    |                                                                  ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:162:46: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
162 |       SubscriptSqlExpr e1 e2 -> ppSqlExpr e1 <> brackets (ppSqlExpr e2)
    |                                              ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:166:40: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
166 |       FunSqlExpr f es        -> text f <> parens (commaH ppSqlExpr es)
    |                                        ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:171:45: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
171 |       CastSqlExpr typ e      -> text "CAST" <> parens (ppSqlExpr e <+> text "AS" <+> text typ)
    |                                             ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:173:46: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
173 |       ArraySqlExpr es        -> text "ARRAY" <> brackets (commaH ppSqlExpr es)
    |                                              ^^

src/Opaleye/Internal/HaskellDB/Sql/Print.hs:175:50: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:7:8-43
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at src/Opaleye/Internal/HaskellDB/Sql/Print.hs:30:53-56
    |
175 |       AggrFunSqlExpr f es ord distinct -> text f <> parens (ppSqlDistinct distinct <+> commaH ppSqlExpr es <+> ppOrderBy ord)
    |                                                  ^^
cabal: Leaving directory '/var/folders/kv/4xxz5fvd7jq8pwkkr4j1dlj40000gn/T/cabal-tmp-46623/opaleye-0.6.7000.0'
cabal: Error: some packages failed to install:
opaleye-0.6.7000.0-2zLcmx53TlnJY34QVAuO33 failed during the building phase.
The exception was:
ExitFailure 1
```

### PR DESCRIPTION
**Pull request by saurabhnanda**
Fixes #394

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
All good but please revert the Zip change

**Comment by tomjaguarpaw** [comment]
(or more precisely, remove it from the PR)

**Comment by saurabhnanda** [comment]
Done

**Comment by tomjaguarpaw** [comment]
Great.  I'll wait for the check to pass, which I assume will because it did previously :)

**Comment by tomjaguarpaw** [comment]
Although I am still extremely puzzled why the checks passed previously without this patch.

**Comment by tomjaguarpaw** [comment]
Oh, this already existed since the last Hackage release: https://github.com/tomjaguarpaw/haskell-opaleye/commit/5377df0219db3d36257e574a242ed8f60442bb6b.  Now we're hiding `<>` twice :)

OK, I'll close this and just release `master` to Hackage.

**Comment by tomjaguarpaw** [comment]
I'll also add your Stackage bump when I get round to it.  Feel free to submit it as a PR on its own if you want it done quicker.

**Pull request closed without merging**
