### PR TITLE
Enabled cache on Travis to speed up build

### PR DESCRIPTION
**Pull request by ilya-murzinov**
I've noticed that Travis build takes about 1 hour now.
This should speed it up.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Can you explain what this does?  Building Opaleye does not take long.  Probably less than one minute.  It's installing all the supporting packages and running the tests that take most of the time.

FWIW, the Travis build takes about 10 minutes per GHC version.  We test in parallel so the total time is a bit more than 10 minutes, not 1 hour.

**Comment by ilya-murzinov** [comment]
Sorry, I got confused by Travis :)
Seems that it adds durations of every single test tun.
screen shot 2017-10-09 at 13 53 32

> It's installing all the supporting packages and running

That is what caching is for. It will cache installed packages so next time you run tests it will take far less time.

I'm not sure why this doesn't work though...

**Comment by ilya-murzinov** [comment]
Yeah, got this.
```
neil: .travis.yml file mismatch
Wanted:
sudo: required
env:
- GHCVER=7.6.3
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.1
- GHCVER=head
script:
- curl -sL https://raw.github.com/tomjaguarpaw/neil/master/travis.sh | sh
Got:
sudo: required
env:
- GHCVER=7.6.3
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.1
- GHCVER=head
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - .stack-work
script:
- curl -sL https://raw.github.com/tomjaguarpaw/neil/master/travis.sh | sh
```

`neil` requires specific `.travis.yml` file.
This is funny.

**Comment by ilya-murzinov** [comment]
@tomjaguarpaw can you tweak `neil`? it will REALLY speed up the build.

**Comment by ilya-murzinov** [comment]
Or maybe just migrate to `stack`?
It doesn't support 7.6, but otherwise should be perfectly fine.

**Comment by tomjaguarpaw** [comment]
I think maybe you have to put the `cache` entry below the `script` entry.  IIRC the `script` entry and everything above it is checked by `neil`.  You are free to vary the bits below it.

**Comment by ilya-murzinov** [comment]
Yay! Works now!
And takes twice less time.

**Comment by tomjaguarpaw** [comment]
That's a good improvement.  Can you tell me exactly what it is caching?

**Comment by tomjaguarpaw** [comment]
Well, I guess I can see it is caching `.ghc`, `.cabal`, etc.!  Really what I want to know is when the cache is invalidated.

**Comment by ilya-murzinov** [comment]
Cache can be invalidated manually in Travis.

**Comment by ilya-murzinov** [comment]
But from my experience, this is virtually never required.

**Comment by tomjaguarpaw** [comment]
OK, this looks cool!  Given that the Travis build does not use Stack can we remove the lines

    - $HOME/.stack 
    - .stack-work

**Comment by ilya-murzinov** [comment]
removed

**Comment by tomjaguarpaw** [comment]
There was a build failure which wasn't your fault.  I've restarted the effected build.

**Comment by tomjaguarpaw** [comment]
Great, thanks!  Looking forward to having  faster builds!

**Pull request merged**
