### PR TITLE
implement IN and NOT IN the terms of OR and AND #21

### PR DESCRIPTION
**Pull request by coubeatczech**
I also need this, let's have this in Opaleye!

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks for that. 

* Shouldn't `in_` and `notIn` be generalised to `Foldable`?
* Should it be `foldl'` not `foldr`?  The result can't be consumed lazily, so I would guess so.  On the other hand, maybe future potential optimisations could take advantage of laziness.  Anyway, it's probably not a big deal.
* Do we really need `notIn`?

**Comment by coubeatczech** [comment]
* that's right, I added `Foldable` context
* ok, that's right, let's use strict fold
* I don't see why there shouldn't exist any case where `notIn` is needed, is it already expressable with something else?

**Comment by tomjaguarpaw** [comment]
Sure, `notIn x y == not (in_ x y)`.

**Comment by coubeatczech** [comment]
Now I fell a little stupid :-).
We also save chars, because `length "OR" < length "AND"` :-)

**Comment by tomjaguarpaw** [comment]
No need to feel stupid :-)

**Comment by tomjaguarpaw** [comment]
I will leave it up to you whether to keep it or remove it.  You made the patch so you get to decide.

**Comment by bergmark** [comment]
I also suggested notIn :astonished:

**Comment by tomjaguarpaw** [comment]
We may as well still have `ands` though!

**Pull request merged**
