### PR TITLE
Update stack.yaml

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Will this pin `product-profunctors` to version `0.7.1.0` for `opaleye` too?  Is it possible to give different `extra-deps` for the different packages?

If not I suggest we just kick `opaleye-sqlite` out of this `stack.yaml`.  It's not up to date or really supported at all.

**Comment by mitchellwrosen** [comment]
> Will this pin product-profunctors to version 0.7.1.0 for opaleye too? Is it possible to give different extra-deps for the different packages?

Yep and nope.

> If not I suggest we just kick opaleye-sqlite out of this stack.yaml. It's not up to date or really supported at all.

Sure.

**Comment by tomjaguarpaw** [comment]
> > Will this pin product-profunctors to version 0.7.1.0 for opaleye too? Is it possible to give different extra-deps for the different packages?

> Yep and nope.

Seems a bit strange.  Perhaps you're supposed to have two different `stack.yaml`s if you want to have different dependencies.

**Comment by saurabhnanda** [comment]
I can confirm that this stack file works, and can be merged.

**Comment by tomjaguarpaw** [comment]
Thanks very much.

**Pull request merged**
