### PR TITLE
Postgres treats upper case letters in type names as lower case,

### PR DESCRIPTION
**Pull request by stevemao**
unless the name is quoted!

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Ah, good catch, thank you. I'm rather backlogged at the moment but I'll get to this as soon as I can.

**Comment by tomjaguarpaw** [comment]
Cool, thank you. Please let me know if you need me to make a release containing this.

**Comment by stevemao** [comment]
a new release would be nice. So I can remove my workaround 😄

**Comment by tomjaguarpaw** [comment]
OK done! https://hackage.haskell.org/package/opaleye-0.7.5.0

**Comment by stevemao** [comment]
@tomjaguarpaw do you mind pushing the commit and the tag? incase the version confuses people

**Pull request merged**
