### PR TITLE
Simple BYTEA support

### PR DESCRIPTION
**Pull request by llelf**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Very nice.  Thanks.

**Comment by bergmark** [comment]
@tomjaguarpaw any chance of getting a release soon? It seems like there are only non breaking changes since the last release. We're currently using opaleye from master to get the latest stuff.

**Comment by tomjaguarpaw** [comment]
Sure, done.  Feel free to ping me whenever you need a release.

http://hackage.haskell.org/package/opaleye-0.3.1

**Comment by bergmark** [comment]
thanks, will do!

**Pull request merged**
