### PR TITLE
Added union

### PR DESCRIPTION
**Pull request by andrewthad**
If this gets merged as is, I'll add in all the other binary operations using the same approach.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
You need to export the explict versions too (though ideally the unexported stuff should be in the `Internal` module).

**Comment by andrewthad** [comment]
Ah. I'll move that to an internal module.

**Comment by andrewthad** [comment]
It has now been moved and the export list deleted.

**Comment by tomjaguarpaw** [comment]
That's great, thanks.  We've been missing that for a long time!

**Pull request merged**
