### PR TITLE
Allow 'ORDER BY' in aggregation functions.

### PR DESCRIPTION
**Pull request by hesselink**
This implements the ordering within aggregates as discussed in #153.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks Erik.

Firstly, this needs a test.

Secondly, you have

    orderAggregate o (Aggregator (PM.PackMap pm)) =
        Aggregator (PM.PackMap (\f c -> pm (f . P.first' (fmap (P.second' (++ O.orderExprs c o)))) c))

Did you mean to append the `orderExprs`, or did you mean to overwrite them?  I thought you wanted to do the latter.

**Comment by tomjaguarpaw** [comment]
Otherwise this seems fine.

**Comment by tomjaguarpaw** [comment]
Oh, and can you import `<$>` explicitly please?

**Comment by tomjaguarpaw** [comment]
I don't care about warnings on later GHCs.

**Comment by hesselink** [comment]
> Firstly, this needs a test.

Yup, that was on my todo list as well.

> Did you mean to append the orderExprs, or did you mean to overwrite them? I thought you wanted to do the latter.

Indeed, but it's pretty clear I didn't :) I'll add a test for this when I fix it.

> I don't care about warnings on later GHCs.

I meant to ask about that, since currently it's pretty hard for me (on GHC 7.10) to see things like incomplete pattern matches through the noise. So you're not interested in any of the fixes mentioned [in the migration guide](https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10#GHCsaysTheimportof...isredundant)?

**Comment by tomjaguarpaw** [comment]
My thoughts on warnings

1. I agree that it's good to see important warnings clearly.
2. I agree that unimportant warnings are a drawback.
3. I don't mind the code changing so that the redundant warning noise is borne by older GHCs, leaving the newer ones clearer.
4. If you want to make the code warning free on 7.10 that's fine, as long as it still compiles on 7.6 and 7.8.  I just can't be bothered to do it myself.
5. Incomplete pattern matches should be an error.  Can we convince GHC to make it so?

**Comment by hesselink** [comment]
OK, sounds good, I might give it a go next time I'm bothered by it. Sadly 5 isn't currently possible but would be really nice. It's [GHC ticket 11219](https://ghc.haskell.org/trac/ghc/ticket/11219).

**Comment by tomjaguarpaw** [comment]
That feature would be good.

OK, you're welcome to change things around warnings.  By "I don't care about warnings on later GHCs" I meant "I personally don't mind but you're welcome to improve them if you feel like it".

**Comment by hesselink** [comment]
I've fixed the bug, fixed the build on 7.8 and added tests. I don't think there was anything else, so unless you have some more feedback, I think this is done.

**Comment by tomjaguarpaw** [comment]
This is really excellent stuff!  Thanks.

**Pull request merged**
