### PR TITLE
Add the ability to distinctily aggregate

### LINKED ISSUE #164: Support for COUNT(DISTINCT x)
I can only see the `count` aggregate, but that doesn't let me apply the distinct condition on the expression being counted.

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #164

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Cool, thanks!  Hopefully I'll be able to look over this tonight.

**Comment by ocharles** [comment]
I have some code doing max/min/countDistinct in my wrapper over opaleye and it seems to do the right thing

**Comment by tomjaguarpaw** [comment]
Could you add a test in `Test.hs`?  I think you could just adjust/expand one of the existing tests rather than add a whole new one.

**Comment by tomjaguarpaw** [comment]
This looks good.  Some comments:

1. It will need at least one test in `Test.hs`.

2. Please change the definition of `distinct'` to a `case`: https://github.com/tomjaguarpaw/haskell-opaleye/pull/165/files#diff-cc1cf4700a323e9e566917c89269d428R126

3. Will `aggregateDistinct` be sufficient for you?  It will force *all* aggregators to be done with `DISTINCT`.  If this is really all you want why not use `distinct` before doing a normal aggregation?

**Comment by ocharles** [comment]
No, I want to count distinct and take a max and min in the same
aggregation. However I don't think I use the Opaleye surface API (will have
to check) for this so you might be OK changing it.

**Comment by tomjaguarpaw** [comment]
On Thu, May 05, 2016 at 03:37:33PM -0700, Oliver Charles wrote:
> No, I want to count distinct and take a max and min in the same
> aggregation. However I don't think I use the Opaleye surface API (will have
> to check) for this so you might be OK changing it.

I'm not sure what you mean.  Can you be more precise?

**Comment by ocharles** [comment]
About which bit? I am writing opaleye-tf which is mostly using .Internal
modules

**Comment by tomjaguarpaw** [comment]
On Fri, May 06, 2016 at 01:26:50AM -0700, Oliver Charles wrote:
> About which bit? I am writing opaleye-tf which is mostly using .Internal
> modules

Do you mean you're not using the `aggregageDistinct` that you wrote?

**Comment by ocharles** [comment]
Not at the moment, no - we have our own `Aggregator` like thing: https://github.com/ocharles/opaleye-tf/blob/d8f4c7e36573b120afe9b42eccfc531a2e0d2514/src/Opaleye/TF.hs#L585.

**Comment by ocharles** [comment]
I'm not quite sure what you're saying about `aggregateDistinct`. You say it will force all aggregations to be done with distinct, but surely if I just do something like '(,) <$> lmap foo count <*> lmap bar aggregateDistinct count` I would only distinctly count bar? That was my intention, anyway.

**Comment by tomjaguarpaw** [comment]
Sorry, I misunderstood what it does.  Could you call it `distinctAggregator` then, so it doesn't resemble `aggregateOrdered`?

**Comment by tomjaguarpaw** [comment]
That patch failed due to something unrelated.  I've kicked off the build again.

**Comment by ocharles** [comment]
Could this be merged?

**Comment by ocharles** [comment]
Oh bah, I seem to have messed up my branch.

**Comment by tomjaguarpaw** [comment]
?

**Comment by tomjaguarpaw** [comment]
Oh I see.  You've reopened it here: https://github.com/tomjaguarpaw/haskell-opaleye/pull/278

**Pull request closed without merging**
