### PR TITLE
Distinct aggregates

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Was previously https://github.com/tomjaguarpaw/haskell-opaleye/pull/165

**Comment by tomjaguarpaw** [comment]
Could you rename the function [as requested](https://github.com/tomjaguarpaw/haskell-opaleye/pull/165#issuecomment-217442059)?

**Comment by ocharles** [comment]
Ok, done.

**Comment by tomjaguarpaw** [comment]
Can you make it build on 7.6 please?

**Pull request merged**
