### PR TITLE
Add IsString (Column ...) instances

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This adds IsString instances for
- Column PGText
- Column PGBytea
- Column PGJson
- Column PGJsonb

Addresses #107

### CODE REVIEW

**Comment by bergmark** [comment]
Are the json instances partial? I'd like to avoid that.

**Comment by mitchellwrosen** [comment]
I'm think so... they're as partial as `pgJSON` and `pgJSONB`.

**Comment by tomjaguarpaw** [comment]
Thanks for this.  Can you explain why you introduced `PGStringRep` rather than just implementing the `IsString` instances directly?

I'm certainly happy for `PGText` to have an `IsString` instance, but like @bergmark I'd prefer to avoid them being partial, even at the PG-runtime level.  I'm also not entirely conivnced of the utility of the instance for `bytea`, but feel free to persuade me!

**Comment by mitchellwrosen** [comment]
`instance String (Column PGText)` is definitely ideal. I just threw this patch together after wrestling with some cyclic dependency issues. 

Without some restructuring of the modules, I'm not sure what file this instance is supposed to be written in :)

**Comment by tomjaguarpaw** [comment]
There are `Num` instances in `Internal.Column`, so I'd put an `IsString` instance there too.

**Comment by tomjaguarpaw** [comment]
Oh wait, now I understand what you mean about the cyclic dependencies!  OK, this needs some thinking about ...

**Comment by tomjaguarpaw** [comment]
My suggestion is that we keep basically what you've already got, but with

    pgFromString :: String -> Column a

and get rid of the type families.  Let's only provide an instance for `PGText` for now.  If you make those changes and squash your commits into one I'm happy to merge!  Thanks.

**Comment by mitchellwrosen** [comment]
Do you mean this?

```haskell
class PGString a where
    pgFromString :: String -> Column a

instance PGString a => IsString (Column a) where
    fromString = pgFromString

instance PGString PGText where
    pgFromString = pgString
```

**Comment by tomjaguarpaw** [comment]
Yes, exactly that!

**Comment by mitchellwrosen** [comment]
Sure thing, updated.

**Comment by tomjaguarpaw** [comment]
Cool, thanks.

**Pull request merged**
