### PR TITLE
infixr 3 .&&

### PR DESCRIPTION
**Pull request by roelvandijk**
- Fixes regression caused by 4fb62fdfb995aa257f303b077047ca52f5f15009

### CODE REVIEW

**Comment by roelvandijk** [comment]
Note that the `.&&` operator in `Opaleye.Internal.Operators` has the correct fixity. Why not simply re-export that symbol?

Note that you can set the [`not-home` module attribute](https://www.haskell.org/haddock/doc/html/module-attributes.html) for internal modules if you want nice Haddock documentation that includes internal symbols.

**Comment by tomjaguarpaw** [comment]
Ah, it was for Haddock that I did it.  I will revert that change and look into `not-home`.

**Comment by tomjaguarpaw** [comment]
Merged your patch so you have a fixed repo to work with and then I'll do the `not-home` stuff.

**Comment by tomjaguarpaw** [comment]
Thanks, I uploaded this fix as 0.5.2.2 to Hackage.

**Pull request merged**
