### PR TITLE
Mimic operator names in BinOp constructors

### PR DESCRIPTION
**Pull request by roelvandijk**
`BinOp` constructors are renamed to syntactically match the corresponding PostgreSQL operators.

Some operators have names which are not valid Haskell operators (`AND`, `LIKE`, `MOD`). I did not changes names in those instances.

One outlier is the comparison operator `=`. I chose to represent it as `:==` in Haskell in order to distinguish it from the assignment operator `:=`. 

The advantage of these new names is that the DSL more closely matches the target SQL language.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
I like this!  One question: why `.==` instead of `.=`?

**Comment by roelvandijk** [comment]
Because equality testing and assignment use the same operator in PostgreSQL.

**Comment by tomjaguarpaw** [comment]
Fair enough.  I think this is a good idea.  The only thing that can go wrong is if two morally distinct operators have the same symbol (exactly as in the case of `=` and `==`) but I think we'll deal with that as we come to it.

**Comment by roelvandijk** [comment]
I think operators having the same symbol will be very rare. It also leads to problems in PostgreSQL's grammar.

**Comment by tomjaguarpaw** [comment]
Cool. I'm happy to accept this.  I'm rerunning one of the tests since I think it had a spurious failure.

**Comment by tomjaguarpaw** [comment]
This is very cool, thanks!

**Comment by roelvandijk** [comment]
No problem. I'm enjoying using opaleye.

**Pull request merged**
