### PR TITLE
Provide a cursor interface useful for writing streaming producers

### PR DESCRIPTION
**Pull request by basvandijk**
This is useful for writing streaming producers. See the [following discussion on the haskell-pipes list](https://groups.google.com/forum/#!topic/haskell-pipes/lRtRtibmq9U).

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This looks great, thanks!

`prepareQuery` only returns `Nothing` when the query is guaranteed to have zero rows. I don't think it's wise to infect the type of `declareCursor` with this internal information.  Could we put knowledge of this into the `Cursor` type?  For example

data Cursor haskells = EmptyCursor | Cursor (FR.RowParser haskells) PGSC.Cursor 

I'm somewhat disinclined to remove `module Opaleye.RunQuery` from the exports because then there's a risk that I forget to export something.  Is there a reason this can't remain, perhaps at the bottom of the export list?

**Comment by basvandijk** [comment]
> prepareQuery only returns Nothing when the query is guaranteed to have zero rows. I don't think it's wise to infect the type of declareCursor with this internal information. Could we put knowledge of this into the Cursor type?

I had this initially but I didn't like that in this case `foldForward` has to perform a case analysis each time it's called. However, I now think might be a premature optimisation so I'll go with your suggestion.

> I'm somewhat disinclined to remove module Opaleye.RunQuery from the exports because then there's a risk that I forget to export something. Is there a reason this can't remain, perhaps at the bottom of the export list?

I think it's better if Cursor is an abstract datatype. This ensures we can modify its implementation later without affecting users. If everything is exported by default Cursor is not abstract anymore.

**Comment by tomjaguarpaw** [comment]
> I had this initially but I didn't like that in this case foldForward has to perform a case analysis each time it's called. However, I now think might be a premature optimisation so I'll go with your suggestion.

Great.  Let me know when you've updated the PR.

> I think it's better if Cursor is an abstract datatype. This ensures we can modify its implementation later without affecting users. If everything is exported by default Cursor is not abstract anymore.

Oh right.  Please define it in `Opaleye.RunQuery.Internal` then, and reexport the type from `Opaleye.RunQuery`.  The policy of Opaleye is that everything should be exported.  Things that are internals and unsupported go in `Internal` modules.

**Comment by tomjaguarpaw** [comment]
By the way, it's also Opaleye policy to support back to GHC 7.6, so you'll need to import `pure` and `<$>`.

**Comment by basvandijk** [comment]
Sure will do!

**Comment by basvandijk** [comment]
What about this?

**Comment by tomjaguarpaw** [comment]
This looks great.  I'm just waiting for the tests to finish.  This should be a formality, since your commit is not changing anything tested!

**Comment by tomjaguarpaw** [comment]
Oops, didn't mean to close.

**Comment by tomjaguarpaw** [comment]
Thanks, that's great!

**Comment by basvandijk** [comment]
Thanks!

When do you expect you'll publish a new release?

**Comment by tomjaguarpaw** [comment]
Just now :) https://hackage.haskell.org/package/opaleye-0.5.4.0

**Pull request merged**
