### PR TITLE
compatibility fixes for GHC 8.4.x

### PR DESCRIPTION
**Pull request by saurabhnanda**
Fixes https://github.com/tomjaguarpaw/haskell-opaleye/issues/394

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Can you move the stack bump into a different commit?

**Comment by tomjaguarpaw** [comment]
Are you looking at this?

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/Table.hs#L182

In what way is it circular?

**Comment by tomjaguarpaw** [comment]
I also don't understand why this conflicts.

**Comment by saurabhnanda** [comment]
> Can you move the stack bump into a different commit?

I've moved it into a different **commit**. Unless you meant a  different **PR**

**Comment by saurabhnanda** [comment]
> In what way is it circular?

`mappend` is in `Monoid` and `Semigroup` is a **superclass** of `Monoid` now.

**Comment by tomjaguarpaw** [comment]
> I've moved it into a different commit. Unless you meant a different PR

A different commit is fine.

**Comment by tomjaguarpaw** [comment]
> >  In what way is it circular?

> mappend is in Monoid and Semigroup is a superclass of Monoid now.

That's fine.  You can define superclass instances using subclass methods, for example `pure = return` is fine.

**Comment by tomjaguarpaw** [comment]
Can you remove the change to `Zip` (or demonstrate that it's necessary)?  I'm happy to take the stack bump and the hiding of `<>` (assuming it builds on earlier GHCs).

**Comment by tomjaguarpaw** [comment]
Can you also rebase this on `master`?  I'm not sure why it was branched from an earlier version.

**Comment by saurabhnanda** [comment]
As an immediate fix to the version released on Hackage. Not sure what else
is there on master, and how stable it is for a Hackage release.

**Comment by tomjaguarpaw** [comment]
I'm happy to release `master` + this PR on Hackage.

**Comment by tomjaguarpaw** [comment]
Yes, please still rebase on master.

**Comment by saurabhnanda** [comment]
https://github.com/tomjaguarpaw/haskell-opaleye/pull/396

> That's fine. You can define superclass instances using subclass methods, for example pure = return is fine.

I missed this. Do you want me to revert this particular change that I introduced? (although it seems logically more consistent).

**Comment by tomjaguarpaw** [comment]
> Do you want me to revert this particular change that I introduced? 

Yes please.

**Comment by saurabhnanda** [comment]
Done

**Pull request closed without merging**
