### PR TITLE
Add json operators

### PR DESCRIPTION
**Pull request by roelvandijk**
Partially implements #143.

Adds the operators specified in https://www.postgresql.org/docs/9.4/static/functions-json.html.

Note that `.@>`, `.<@`, `.?`, `.?|` and `.?&` have a stricter type than specified by PosgreSQL. In PostgreSQL their operands may be `null`. I think the not null variants are more useful in practice.

In order to overload `.->` and `.->>` I created two type classes. A user could easily make a type like `PGInt4` an instance of `IsPGJson` allowing queries to be written that crash at runtime. To prevent that I used the private super class trick.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This looks great!  Could you add some tests please?

**Comment by roelvandijk** [comment]
Sure! I added some tests.

**Comment by roelvandijk** [comment]
Could the Travis test failure be the result of an older version of Postgresql which does not yet have the `jsonb` type?

**Comment by tomjaguarpaw** [comment]
It uses Postgres 9.3, so you are correct, it does not have `jsonb`.  Let's just skip `jsonb` checks for now, as they are exactly the same as the `json` ones.

**Comment by roelvandijk** [comment]
Ok, I'll comment out the jsonb tests and force push the result.

**Comment by tomjaguarpaw** [comment]
It would be good if you could add them to another list of tests which is compiled but not run.  Then we can easily enable them in the future.

**Comment by roelvandijk** [comment]
Good idea, I'll do that

**Comment by roelvandijk** [comment]
Oops. Forgot the table creation functions

**Comment by roelvandijk** [comment]
Yay, finally builds!

I realized I can also make the jsonb testing code dependent on **not** running on travis.

Something like:
```haskell
jsonbResults <- case travis' of 
  True -> []
  False -> do
    mapM_ (PGS.execute_ conn . dropAndCreateTableJsonb) jsonbTables
    insert (table9, table9columndata)
    mapM ($ conn) jsonbTests
```

Would that be useful?

**Comment by roelvandijk** [comment]
Ok, last idea for today. What are you thoughts on adding the json operators to the `PrimQuery` language?

I would be happy to add some constructors to `BinOp` and some SQL translations to `showBinOp`.

Something like:
```haskell
data BinOp = ...
           | OpJsonGet              -- "->"
           | OpJsonGetText          -- "->>"
           | OpJsonGetPath          -- "#>"
           | OpJsonGetPathText      -- "#>>"
           | OpJsonbLeftWithinRight -- "@>"
           | OpJsonbRightWithinLeft -- "<@"
           | OpJsonbContains        -- "?"
           | OpJsonbContainsAny     -- "?|"
           | OpJsonbContainsAll     -- "?&"
```

**Comment by tomjaguarpaw** [comment]
I think it's a good idea.  The only downside is that the names don't correspond to the symbols at all.  I'll leave it up to you.  If you want to do it, please do.  If not, no problem.

**Comment by roelvandijk** [comment]
The naming part is hard. An alternative is to use symbols as names.

Simply use `:.->` or `:->` as the constructor corresponding to `.->`. Likewise for the other operators.

A downside to using symbols is that it is not symmetrical with the other operator constructors. Unless you also change them to symbols.

**Comment by tomjaguarpaw** [comment]
Using type operators is a clever idea!  Please submit a separate PR and I'll have a look at it.

**Comment by roelvandijk** [comment]
If #194 is appealing I can do the same for the json operators.

**Comment by roelvandijk** [comment]
I fixed a typo. Now the test suite is happy again.

If necessary I can rebase all 3 commits into a single commit.

I noticed that there is some minor overlap possible with #156. Namely the `<@` and `@>` operators are also used by [ranges](https://www.postgresql.org/docs/9.5/static/functions-range.html#RANGE-OPERATORS-TABLE). This can be solved in time using overloading. Same as for `+`, `-`, `*` and friends (who are also defined for ranges).

**Comment by tomjaguarpaw** [comment]
This looks fantastic.  I have one last group of requests:

* Can you rename `IsPGJson` to `PGJson`.  We already have `PGNum`, `PGFractional` etc..
* Can you remove `InternalIsPGJson` and just use `PGJson`?  I agree with your rationale but we don't use the hidden superclass trick for any other of our typeclasses so let's be consistent and not use it here either.

**Comment by roelvandijk** [comment]
I didn't think of the relation with the existing classes. Good call.

I'll add a small warning to the `PGJson` and `JsonIndex` classes to discourage users from making instances.

Also `PGJsonIndex` instead of `JsonIndex` perhaps? It is the class of types which can be used as json keys or indexes in PostgreSQL.

**Comment by tomjaguarpaw** [comment]
> I'll add a small warning

Good idea.

> Also PGJsonIndex instead of JsonIndex perhaps?

And another good idea.

**Comment by roelvandijk** [comment]
Problem: `PGJson` is already the name of a type. This conflicts with the proposed class name.

```haskell
data PGJson
data PGJsonb
```
Need to think of another name for our bikeshed :-)

```haskell
class PGJsonLike a
```
?

**Comment by tomjaguarpaw** [comment]
That's fine, or you could use `PGIsJson` :)

**Comment by tomjaguarpaw** [comment]
It's up to you.  I'll be happy with either of those.

**Comment by roelvandijk** [comment]
Done. I went with `PGIsJson` :-)

Would you like the commits rebased into a single commit?

**Comment by tomjaguarpaw** [comment]
Yes, please rebase and I'll merge after it goes through Travis.

**Comment by tomjaguarpaw** [comment]
Rebased this here: https://github.com/tomjaguarpaw/haskell-opaleye/pull/201

**Comment by tomjaguarpaw** [comment]
Merged this here

https://github.com/tomjaguarpaw/haskell-opaleye/pull/201

**Pull request closed without merging**
