### PR TITLE
Add support for date_trunc

### PR DESCRIPTION
**Pull request by njaremko**
Adds support for [date_trunc](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC)

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks! To start with I'd just prefer two functions: `dateTruncTimestamp` and `dateTruncTimestamptz`. Feel free to make that change, or I can do it when I get round to it.

**Comment by njaremko** [comment]
> dateTruncTimestamp

Done

**Comment by tomjaguarpaw** [comment]
Thanks! I'll try to get round to this at the weekend.

**Comment by tomjaguarpaw** [comment]
Great, thanks!

**Comment by tomjaguarpaw** [comment]
Released in https://hackage.haskell.org/package/opaleye-0.10.2.0

**Pull request merged**
