### PR TITLE
Added possibility of inserting multiple rows with returning values

### LINKED ISSUE #131: How to do a runInsertManyReturning?
I am getting started with Opaleye and find myself wanting to do a `runInsertManyReturning` as I want to insert many values at once, returning an id for each row inserted. In Opaleye, we can only either do `runInsertReturning` or `runInsertMany`.

I only see this functionality in the "opaleye-trans" package: [insertManyReturning](https://hackage.haskell.org/package/opaleye-trans-0.2.0/docs/Opaleye-Trans.html#v:insertManyReturning) where the documentation lists it as:
>Maybe not worth defining. This almost certainly does the wrong thing.

Is there a reason I cannot do this with Opaleye? Is it considered bad practice?

For the record, I have limited experience with Sql.
What I want to do is a:
`INSERT INTO dbname VALUES (_, _,_), (_, _, _) RETURNING id;`

### PR DESCRIPTION
**Pull request by tusj**
Fixes #131

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Cool!  This is a good improvement to the API.

Please don't delete the old function though.  We need to maintain API compatibilty.  Could you look into the build error too, please?

**Comment by tusj** [comment]
I didn't see the travis integration when uploading, I'll look into it.

**Comment by tomjaguarpaw** [comment]
It may well be that Travis is just broken.  The opaleye Travis page seems to be not responding properly.

**Comment by tusj** [comment]
I looked into it. It's me removing the API discussed which is causing the
error.

2015-12-11 12:39 GMT+01:00 tomjaguarpaw <notifications@github.com>:

**Comment by tusj** [comment]
I have readded the `insert..returning` for single inserts, as per aec9e99. Travis works, except for GHC Head, where fails on the dependency resolution but still returns success..

**Comment by tomjaguarpaw** [comment]
Looks great!  Can you rebase all the commits into one?  Then I will merge.

**Comment by tomjaguarpaw** [comment]
A few things need to be fixed before I can merge this

* Documentation patch needs to be reverted and submitted separately
* Whitespace patch needs to be reverted and submitted separately
* `arrangeInsertReturning` needs to be written in terms of `arrangeInsertManyReturning`

Feel free to do them yourself.  If not, I'll do then when I get round to it (hopefully soon).

**Comment by tomjaguarpaw** [comment]
I went ahead and did this.  Thanks for providing the implementation!

https://github.com/tomjaguarpaw/haskell-opaleye/commit/ba5f93ed6149b80518785dd6ffce1c0a6f6a085b

**Comment by tomjaguarpaw** [comment]
This has a passing build as of https://github.com/tomjaguarpaw/haskell-opaleye/commit/8ec14a2edbebf12e0be2165a9a890c1701ca7e64

**Comment by tusj** [comment]
I am sorry could not complete this one. I was a little stuck on the rebase. Have mostly been using git for personal projects so I have only been using it in a basic way. Thanks for finishing it!

**Comment by tomjaguarpaw** [comment]
I agree git is not the most usable tool.

**Pull request closed without merging**
